/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Stitch MCP Design System - Store Rating Platform
        'on-primary-container': '#fffbff',
        'tertiary': '#825100',
        'surface-container-lowest': '#ffffff',
        'background': '#f8f9ff',
        'inverse-primary': '#c0c1ff',
        'on-error-container': '#93000a',
        'surface-dim': '#cbdbf5',
        'error-container': '#ffdad6',
        'surface-tint': '#494bd6',
        'error': '#ba1a1a',
        'on-primary-fixed': '#07006c',
        'on-secondary-fixed-variant': '#6900b3',
        'primary': '#4648d4',
        'on-secondary': '#ffffff',
        'secondary-fixed': '#f0dbff',
        'on-tertiary-fixed': '#2a1700',
        'inverse-on-surface': '#eaf1ff',
        'on-secondary-fixed': '#2c0051',
        'on-primary': '#ffffff',
        'secondary': '#8127cf',
        'surface-variant': '#d3e4fe',
        'on-surface-variant': '#464554',
        'inverse-surface': '#213145',
        'secondary-container': '#9c48ea',
        'outline-variant': '#c7c4d7',
        'tertiary-fixed': '#ffddb8',
        'on-tertiary-fixed-variant': '#653e00',
        'secondary-fixed-dim': '#ddb7ff',
        'primary-fixed-dim': '#c0c1ff',
        'surface-bright': '#f8f9ff',
        'on-tertiary': '#ffffff',
        'on-secondary-container': '#fffbff',
        'on-primary-fixed-variant': '#2f2ebe',
        'primary-container': '#6063ee',
        'surface-container': '#e5eeff',
        'tertiary-fixed-dim': '#ffb95f',
        'on-background': '#0b1c30',
        'tertiary-container': '#a36700',
        'outline': '#767586',
        'surface-container-low': '#eff4ff',
        'on-tertiary-container': '#fffbff',
        'primary-fixed': '#e1e0ff',
        'surface-container-highest': '#d3e4fe',
        'on-surface': '#0b1c30',
        'surface': '#f8f9ff',
        'surface-container-high': '#dce9ff',
        'on-error': '#ffffff',

        // Convenience aliases for existing component classes
        'primary-50': '#e1e0ff',
        'primary-100': '#c0c1ff',
        'primary-500': '#4648d4',
        'primary-600': '#3f41c0',
        'primary-700': '#2f2ebe',
        'surface-50': '#f8f9ff',
        'surface-100': '#eff4ff',
        'surface-200': '#e5eeff',
        'surface-700': '#464554',
        'surface-800': '#213145',
        'surface-900': '#0b1c30',
        
        // Shadcn UI mapped to our CSS variables
        background: 'var(--color-bg-light)',
        foreground: 'var(--color-text-main)',
        muted: {
          DEFAULT: 'var(--color-border)',
          foreground: 'var(--color-text-muted)',
        },
        border: 'var(--color-border)',
        input: 'var(--color-border)',
        ring: 'var(--color-primary)',
        primary: {
          DEFAULT: 'var(--color-primary)',
          foreground: '#FFFFFF',
        },
        accent: {
          DEFAULT: 'var(--color-accent)',
          foreground: '#FFFFFF',
        }
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        lg: '0.75rem',
        xl: '1rem',
        '2xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        xxl: '48px',
        gutter: '24px',
        base: '8px',
        sm: '12px',
        lg: '24px',
        xs: '4px',
        'container-max': '1280px',
        xl: '32px',
        md: '16px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        'headline-xl': ['Inter'],
        'headline-lg': ['Inter'],
        'headline-md': ['Inter'],
        'body-lg': ['Inter'],
        'body-md': ['Inter'],
        'body-sm': ['Inter'],
        'label-md': ['Inter'],
        'label-sm': ['Inter'],
        'display-lg': ['Inter'],
      },
      fontSize: {
        'label-md': ['14px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-lg': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-xl': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
